In [ ]:
#Exercise-1 Create an array with values ranging from 12 to 38

In [2]:
import numpy as np
x = np.arange(12, 38)
print(x)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [ ]:
#Exercise 2 Convert a list and tuple into arrays

In [2]:
lst=[1,2,3]
tupl=(2,4,6)
np.array(lst) # np.asarray can also be used

array([1, 2, 3])

In [3]:
np.array(tupl)

array([2, 4, 6])

In [ ]:
#Exercise 3 Convert the values of Centigrade degrees into Fahrenheit degrees

In [ ]:
#Celsius to fahrenheit
 feh = (9 * cel / 5 + 32)

In [21]:
inp = [0, 12, 45.21, 34, 99.91]
cel=np.array(inp)
print(f"Celsius{cel}")
feh = (9 * cel / 5 + 32)
print(f"Fahrenheit {feh}")

Celsius[ 0.   12.   45.21 34.   99.91]
Fahrenheit [ 32.     53.6   113.378  93.2   211.838]


In [ ]:
 #Exercise 4
    Write a NumPy program to find the number of elements of an array,
length of one array element in bytes and total bytes consumed by the elements

In [3]:
import numpy as np
array1=np.array([1,2,3,4])
print(array1.size)
print(array1.itemsize)
print(array1.nbytes)

4
4
16


In [ ]:
#Exercise 5
Get the unique elements of an array

In [26]:
import numpy as np
array1=np.array([[1,2,3,4,8,],[4,3,2,1,50]])
np.unique(array1) #Unique function is used to remove redundant value

array([ 1,  2,  3,  4,  8, 50])

In [ ]:
#Exercise 6
Change the dimension of an array

In [29]:
array2=np.array([1,2,3,4,5,6,7,8,9])
array2.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
#Exercise 7
#Create a 1-D array of 30 evenly spaced elements between 2.5. and 6.5, inclusive

np.linspace(2.5,6.5,30)

array([2.5       , 2.63793103, 2.77586207, 2.9137931 , 3.05172414,
       3.18965517, 3.32758621, 3.46551724, 3.60344828, 3.74137931,
       3.87931034, 4.01724138, 4.15517241, 4.29310345, 4.43103448,
       4.56896552, 4.70689655, 4.84482759, 4.98275862, 5.12068966,
       5.25862069, 5.39655172, 5.53448276, 5.67241379, 5.81034483,
       5.94827586, 6.0862069 , 6.22413793, 6.36206897, 6.5       ])

In [34]:
#Exercises 8
#Convert 1-D arrays as columns into a 2-D array
array1=np.array([1,2,3,4])
array2=np.array([5,6,7,8])
np.column_stack((array1,array2)) #Column_stack changes two separate 1d arrays to 2d arrays in column wise


array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [35]:
#Exercises 9
#Create a 5x5 matrix with row values ranging from 0 to 4

x = np.zeros((5,5))
print("Original array:")
print(x)
print("Row values ranging from 0 to 4.")
x += np.arange(5)
print(x)

        

Original array:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Row values ranging from 0 to 4.
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [ ]:
#Exercise 10
Sum of all the multiples of 3 or 5 below 100


In [11]:
x = np.arange(1, 100)
n= x[(x % 3 == 0) | (x % 5 == 0)]
print(n)
print(n.sum())


[ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51
 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
2318


In [22]:
#Exercise 11
#Combine a one and a two dimensional array together and display their elements

import numpy as np
x = np.arange(3)
print("One dimensional array:")
print(x)
y = np.arange(6).reshape(2,3)
print("Two dimensional array:")
print(y)
for a, b in np.nditer([x,y]):
    print("%d:%d" % (a,b),)

One dimensional array:
[0 1 2]
Two dimensional array:
[[0 1 2]
 [3 4 5]]
0:0
1:1
2:2
0:3
1:4
2:5


In [23]:
#Exercise 12
#Write a NumPy program to replace all elements of NumPy array that are greater than specified array
import numpy as np
x = np.array([[ 0.42436315, 0.48558583, 0.32924763], [ 0.7439979,0.58220701,0.38213418], [ 0.5097581,0.34528799,0.1563123 ]])
print("Original array:")
print(x)
print("Replace all elements of the said array with .5 which are greater than .5")
x[x > .5] = .5
print(x)


Original array:
[[0.42436315 0.48558583 0.32924763]
 [0.7439979  0.58220701 0.38213418]
 [0.5097581  0.34528799 0.1563123 ]]
Replace all elements of the said array with .5 which are greater than .5
[[0.42436315 0.48558583 0.32924763]
 [0.5        0.5        0.38213418]
 [0.5        0.34528799 0.1563123 ]]


In [41]:
#Exercise 13
#Add a new row to an empty numpy array
import numpy as np
array3= np.arange(0)
print(array3)
arrey1=[1,2,3]
arrey2=[2,4,6]
array3=np.stack((arrey1,arrey2),axis = 0)
print(array3)

[]
[[1 2 3]
 [2 4 6]]


In [ ]:
#Exercise 15
Write a NumPy program to join a sequence of arrays along a new axis

In [ ]:
no idea

In [ ]:
#Exercise 16
Add a border around an existing array(no idea)